package main

import (
	"encoding/json"
	"fmt"
	"io/ioutil"
)

func main() {
	hw, err := GetHardware()
	if err != nil {
		panic(err)
	}
	hwJSON, _ := json.Marshal(hw)
	println(string(hwJSON))

	b, err := ioutil.ReadFile("/home/nick/Desktop/molitor.json")
	if err != nil {
		fmt.Print(err)
	}

	data := AutoGenerated{}
	err = json.Unmarshal(b, &data)
	if err != nil {
		fmt.Print(err)
	}
	fmt.Print("CID: ", data.Customerid, " - ", "location: ", data.Location, " - ", "OS: ", data.Distribution, "\n")

}
